name: Playwright Tests
on:
  push:
    branches: [rewrite]
  pull_request:
    branches: [rewrite]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # TODO: cache deps
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          BASE_URL: "http://localhost:5173"
          DB_PATH: "db.sqlite3"
          LOHI_TOKEN: "salmon"
          SESSION_SECRET: "secret"
          DISCORD_CLIENT_ID: "123"
          DISCORD_CLIENT_SECRET: "secret"
          SKALOP_WS_URL: "ws://localhost:5900"
          SKALOP_SYSTEM_MESSAGE_URL: "http://localhost:5900/system"
          SKALOP_TOKEN: "secret"
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
